project:
  type: site
  output-dir: docs
  resources:
    - "images/*.svg"

site:
  title: "JoVI"
  image: images/jovi_wordmark.svg
  favicon: images/jovi_logo.svg
  navbar:
    title: false
    logo: images/jovi_wordmark.svg
    logo-alt: JoVI
    type: dark
    left:
      - href: index.qmd
        text: About
      - href: submit.qmd
        text: Submit
      - href: code-of-conduct.qmd
        text: Code of Conduct
      - href: organizers.qmd
        text: Organizers

format:
  html:
    theme: theme.scss
    css: custom.css
    toc: true
    linkcolor: "#9E005D"

execute:
  freeze: auto
