project:
  type: site
  output-dir: docs
  resources:
    - "images/*.svg"

site:
  title: "JoVI"
  image: "images/jovi_wordmark.svg"
  navbar:
    title: "JoVI"
    logo: "images/jovi_wordmark.svg"
    type: light
    background: light
    foreground: dark
    left:
      - href: index.qmd
        text: About
      - href: submit.qmd
        text: Submit
      - href: code-of-conduct.qmd
        text: Code of Conduct

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    include-in-header:
      - head.html

number-sections: true
number-depth: 2

execute:
  freeze: auto
