project:
  type: website
  resources:
    - "images/*.svg"
    - "CNAME"

website:
  title: "JoVI"
  site-url: https://journalovi.org
  image: images/jovi_wordmark.svg
  favicon: images/jovi_logo.svg
  repo-url: https://github.com/journalovi/journalovi.github.io
  repo-actions: [edit, issue]
  navbar:
    title: false
    logo: images/jovi_wordmark.svg
    logo-alt: JoVI
    type: dark
    tools:
      - icon: twitter
        href: https://twitter.com/journalOVI/
        text: JoVI Twitter
      - icon: mastodon
        href: "https://hci.social/%40jovi"
        text: JoVI Mastodon
        rel: me
      - icon: github
        href: https://github.com/journalovi/journalovi.github.io
        text: JoVI Github
    left:
      - href: index.qmd
        text: About
      - href: https://journals.aau.dk/index.php/jovi/issue/current
        text: Current Issue
      - sidebar:submit
      - href: code-of-conduct.qmd
        text: Code of Conduct
      - href: organizers.qmd
        text: Organizers
      - href: news.qmd
        text: News

  page-footer:
    left: |
      Licensed under [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)
    right:
      - icon: twitter
        href: https://twitter.com/journalOVI/
        aria-label: JoVI Twitter
      - icon: mastodon
        href: "https://hci.social/%40jovi"
        aria-label: JoVI Mastodon
      - icon: github
        href: https://github.com/journalovi/journalovi.github.io
        aria-label: JoVI Github

  sidebar:
    - id: submit
      title: "Submissions"
      contents:
        - submit.qmd
        - author-guide.qmd
        - reviewer-guide.qmd

format:
  html:
    theme: theme.scss
    css: custom.css
    toc: true
    linkcolor: "#9E005D"

execute:
  freeze: auto
